// <auto-generated />
namespace PowerUps.MicroServices.PushoverFacade.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TenantApiKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TenantApiKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201406010747134_TenantApiKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
